name: Setup Environment
inputs:
  CACHIX_AUTH_TOKEN:
    required: true
    description: "Cachix Auth Token"
  SECRET_GITHUB_TOKEN:
    required: true
    description: "Github Secret Token"
runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github_token: ${{ inputs.SECRET_GITHUB_TOKEN }}

    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: yaxitech/nix-install-pkgs-action@v3
      with:
        packages: "nixpkgs#nixci"
