name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Example/nixos
        run: nix -Lv build ./local#eval.nixos.expr.nixosConfiguration.config.system.build.toplevel --dry-run

      - name: Run Eval check
        run: nix -Lv eval ./local#checks --override-input namaka github:nix-community/namaka

      - name: Run templates/nixos
        run: nix build ./templates/nixos#nixosConfigurations.nixos.config.system.build.toplevel --dry-run --override-input omnibus ./.
