name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/common-setup
        with:
          SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: nixci
